# data_pipeline/ingest/models.py
"""SQLAlchemy metadata for the ingestion schema (raw + mart + watermarks).

STATCAST_COLUMNS is the pinned manifest of the Savant statcast CSV schema,
derived from a live fetch (2024-06-04) with the *_deprecated columns dropped.
Loading logs any fetched column that is not in this manifest (schema drift)
instead of silently dropping data on the floor. Staging views over these
tables are defined in the Alembic migration (db/migrations/).
"""
from sqlalchemy import (
    BigInteger,
    Column,
    Date,
    DateTime,
    Float,
    Integer,
    MetaData,
    Table,
    Text,
)

metadata = MetaData()

_SQL_TYPES = {"bigint": BigInteger, "float": Float, "text": Text, "date": Date}

# Natural key of a pitch: one row per pitch of one at-bat of one game.
STATCAST_NATURAL_KEY = ("game_pk", "at_bat_number", "pitch_number")

# (column_name, type) in Savant CSV order — the pinned landing schema.
STATCAST_COLUMNS = [
    ("pitch_type", "text"),
    ("game_date", "date"),
    ("release_speed", "float"),
    ("release_pos_x", "float"),
    ("release_pos_z", "float"),
    ("player_name", "text"),
    ("batter", "bigint"),
    ("pitcher", "bigint"),
    ("events", "text"),
    ("description", "text"),
    ("spin_dir", "bigint"),
    ("zone", "bigint"),
    ("des", "text"),
    ("game_type", "text"),
    ("stand", "text"),
    ("p_throws", "text"),
    ("home_team", "text"),
    ("away_team", "text"),
    ("type", "text"),
    ("hit_location", "bigint"),
    ("bb_type", "text"),
    ("balls", "bigint"),
    ("strikes", "bigint"),
    ("game_year", "bigint"),
    ("pfx_x", "float"),
    ("pfx_z", "float"),
    ("plate_x", "float"),
    ("plate_z", "float"),
    ("on_3b", "bigint"),
    ("on_2b", "bigint"),
    ("on_1b", "bigint"),
    ("outs_when_up", "bigint"),
    ("inning", "bigint"),
    ("inning_topbot", "text"),
    ("hc_x", "float"),
    ("hc_y", "float"),
    ("umpire", "bigint"),
    ("sv_id", "bigint"),
    ("vx0", "float"),
    ("vy0", "float"),
    ("vz0", "float"),
    ("ax", "float"),
    ("ay", "float"),
    ("az", "float"),
    ("sz_top", "float"),
    ("sz_bot", "float"),
    ("hit_distance_sc", "bigint"),
    ("launch_speed", "float"),
    ("launch_angle", "bigint"),
    ("effective_speed", "float"),
    ("release_spin_rate", "bigint"),
    ("release_extension", "float"),
    ("game_pk", "bigint"),
    ("fielder_2", "bigint"),
    ("fielder_3", "bigint"),
    ("fielder_4", "bigint"),
    ("fielder_5", "bigint"),
    ("fielder_6", "bigint"),
    ("fielder_7", "bigint"),
    ("fielder_8", "bigint"),
    ("fielder_9", "bigint"),
    ("release_pos_y", "float"),
    ("estimated_ba_using_speedangle", "float"),
    ("estimated_woba_using_speedangle", "float"),
    ("woba_value", "float"),
    ("woba_denom", "bigint"),
    ("babip_value", "bigint"),
    ("iso_value", "bigint"),
    ("launch_speed_angle", "bigint"),
    ("at_bat_number", "bigint"),
    ("pitch_number", "bigint"),
    ("pitch_name", "text"),
    ("home_score", "bigint"),
    ("away_score", "bigint"),
    ("bat_score", "bigint"),
    ("fld_score", "bigint"),
    ("post_away_score", "bigint"),
    ("post_home_score", "bigint"),
    ("post_bat_score", "bigint"),
    ("post_fld_score", "bigint"),
    ("if_fielding_alignment", "text"),
    ("of_fielding_alignment", "text"),
    ("spin_axis", "bigint"),
    ("delta_home_win_exp", "float"),
    ("delta_run_exp", "float"),
    ("bat_speed", "float"),
    ("swing_length", "float"),
    ("miss_distance", "float"),
    ("estimated_slg_using_speedangle", "float"),
    ("delta_pitcher_run_exp", "float"),
    ("hyper_speed", "float"),
    ("home_score_diff", "bigint"),
    ("bat_score_diff", "bigint"),
    ("home_win_exp", "float"),
    ("bat_win_exp", "float"),
    ("age_pit_legacy", "bigint"),
    ("age_bat_legacy", "bigint"),
    ("age_pit", "bigint"),
    ("age_bat", "bigint"),
    ("n_thruorder_pitcher", "bigint"),
    ("n_priorpa_thisgame_player_at_bat", "bigint"),
    ("pitcher_days_since_prev_game", "bigint"),
    ("batter_days_since_prev_game", "bigint"),
    ("pitcher_days_until_next_game", "bigint"),
    ("batter_days_until_next_game", "bigint"),
    ("api_break_z_with_gravity", "float"),
    ("api_break_x_arm", "float"),
    ("api_break_x_batter_in", "float"),
    ("arm_angle", "float"),
    ("attack_angle", "float"),
    ("attack_direction", "float"),
    ("swing_path_tilt", "float"),
    ("intercept_ball_minus_batter_pos_x_inches", "float"),
    ("intercept_ball_minus_batter_pos_y_inches", "float"),
]


raw_statcast_pitches = Table(
    "raw_statcast_pitches",
    metadata,
    *[
        Column(
            name,
            _SQL_TYPES[sql_type](),
            primary_key=name in STATCAST_NATURAL_KEY,
            nullable=name not in STATCAST_NATURAL_KEY,
        )
        for name, sql_type in STATCAST_COLUMNS
    ],
)

raw_bat_tracking = Table(
    "raw_bat_tracking",
    metadata,
    Column("season", Integer, primary_key=True),
    Column("batter_mlbam", BigInteger, primary_key=True),
    Column("name", Text),
    Column("swings_competitive", BigInteger),
    Column("percent_swings_competitive", Float),
    Column("contact", BigInteger),
    Column("avg_bat_speed", Float),
    Column("hard_swing_rate", Float),
    Column("squared_up_per_bat_contact", Float),
    Column("squared_up_per_swing", Float),
    Column("blast_per_bat_contact", Float),
    Column("blast_per_swing", Float),
    Column("swing_length", Float),
    Column("swords", BigInteger),
    Column("batter_run_value", Float),
    Column("whiffs", BigInteger),
    Column("whiff_per_swing", Float),
    Column("batted_ball_events", BigInteger),
    Column("batted_ball_event_per_swing", Float),
)

raw_chadwick_people = Table(
    "raw_chadwick_people",
    metadata,
    Column("key_mlbam", BigInteger, primary_key=True),
    Column("name_first", Text),
    Column("name_last", Text),
    Column("key_retro", Text),
    Column("key_bbref", Text),
    Column("key_fangraphs", BigInteger),
    Column("mlb_played_first", Float),
    Column("mlb_played_last", Float),
)

ingest_watermarks = Table(
    "ingest_watermarks",
    metadata,
    Column("source", Text, primary_key=True),
    Column("chunk_key", Text, primary_key=True),
    Column("status", Text, nullable=False),
    Column("attempt", Integer),
    Column("row_count", BigInteger),
    Column("error", Text),
    Column("started_at", DateTime(timezone=True)),
    Column("completed_at", DateTime(timezone=True)),
)

mart_batter_pitch_season = Table(
    "mart_batter_pitch_season",
    metadata,
    Column("batter_mlbam", BigInteger, primary_key=True),
    Column("season", Integer, primary_key=True),
    Column("full_name", Text),
    Column("pitches", BigInteger),
    Column("swings", BigInteger),
    Column("whiffs", BigInteger),
    Column("whiff_rate", Float),
    Column("zone_rate", Float),
    Column("chase_rate", Float),
    Column("contact_rate", Float),
    Column("batted_balls", BigInteger),
    Column("avg_exit_velo", Float),
    Column("max_exit_velo", Float),
    Column("hard_hit_rate", Float),
    Column("barrel_rate", Float),
    Column("avg_launch_angle", Float),
    Column("measured_swings", BigInteger),
    Column("avg_bat_speed", Float),
    Column("avg_swing_length", Float),
    Column("fast_swing_rate", Float),
)

mart_bat_tracking_season = Table(
    "mart_bat_tracking_season",
    metadata,
    Column("batter_mlbam", BigInteger, primary_key=True),
    Column("season", Integer, primary_key=True),
    Column("full_name", Text),
    Column("competitive_swings", BigInteger),
    Column("avg_bat_speed", Float),
    Column("fast_swing_rate", Float),
    Column("avg_swing_length", Float),
    Column("squared_up_rate", Float),
    Column("blast_rate", Float),
    Column("swords", BigInteger),
    Column("whiff_rate", Float),
    Column("contact", BigInteger),
    Column("whiffs", BigInteger),
    Column("batted_ball_events", BigInteger),
    Column("batter_run_value", Float),
)
